# Generated by Django 4.2.6 on 2023-10-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('file_type', models.CharField(max_length=255)),
            ],
        ),
    ]
