# Generated by Django 4.2.6 on 2023-10-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('variable_no', models.IntegerField()),
                ('variable_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FormCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('form_count', models.IntegerField()),
            ],
        ),
    ]
