# Generated by Django 4.2.6 on 2023-10-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_documentvariables_formcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleGraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('graph_no', models.IntegerField()),
                ('chart_type', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('titel', models.CharField(max_length=255)),
            ],
        ),
    ]
