# Generated by Django 4.2.6 on 2023-10-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_graphlayoutmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='graph_id',
            field=models.CharField(max_length=255),
        ),
    ]
