# Generated by Django 4.2.6 on 2023-10-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_graphlayoutmodel_x_axis_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='bg_color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='graph_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='graph_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='height',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='session_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='width',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='x_axis_end',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='x_axis_sta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='y_axis_end',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='graphlayoutmodel',
            name='y_axis_sta',
            field=models.FloatField(null=True),
        ),
    ]
