# Generated by Django 4.2.6 on 2023-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_graphlayoutmodel_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphlayoutmodel',
            name='graph_title_center',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
