# Generated by Django 4.2.6 on 2023-11-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_graphlayoutmodel_graph_title_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('datetime', models.CharField(max_length=255)),
            ],
        ),
    ]
